### PR TITLE
Immediately stop handling revision and callbacks

### PR DESCRIPTION
**Pull request by garytryan**
### Description

Bug Fix.

Firepad waits until it is ready to dispose. This results in Firepad throwing an error, and updating  the code editor with content before destroying.

This fixes that behavior by removing the callbacks from the destroyed instance, and making the function which updates the code editor a no-op before the instance is. in a ready state.

### CODE REVIEW

**Comment by garytryan** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by samtstern** [comment]
@garytryan thanks for your contribution!  Now that @ mikelehen has left Google I am the de-facto maintainer of Firepad but I am not actually that familiar with it.

Do you have an error log or a demo that explains why this change is necessary?  It looks safe to me but I want to be sure.

**Comment by samtstern** [comment]
Also make sure you sign the CLA with the same email you use on GitHub!

**Comment by mikelehen** [comment]
FWIW while I'm not at Google anymore, I am still keeping an eye on this repo. 😛  The intent of the original code was to make sure we were in a known, initialized state before disposing so that we didn't accidentally continue some initialization tasks, etc. potentially leaving firepad in some sort of zombie state.  I wouldn't have expected it to result in any sort of error, but it was intentionally letting initialization finish before disposing which admittedly is not ideal.

If the old code was causing an error, and the new code avoids that error, then it seems strictly better, though I agree with Sam that it would be good to document what error you were hitting in this PR, and perhaps try to add some comments to the code.

**Comment by garytryan** [comment]
@samtstern @mikelehen Thank you for your quick response! To illustrate what I'm trying to fix I've added two integration tests. I'm happy to clean the tests, I just added these primarily to illustrate and communicate the problems I'm trying to fix. I hope these test help to clarify.

**Comment by garytryan** [comment]
@samtstern Thanks for your feedback regarding the test, and help with the CLA. I've cleaned up the test comments, and have fixed the CLA issues. Let me know they're any other improvements I need to do to get this accepted. Thanks!

**Comment by samtstern** [comment]
@garytryan thanks for everything!

**Pull request merged**
