### PR TITLE
Add Quill Support

### PR DESCRIPTION
**Pull request by larrytin**

### CODE REVIEW

**Comment by kfoxb** [comment]
I'm interested in using Quill with Firepad, I've actually already taken this pull request and used it and it seems to work fine. Besides the conflicting files is there anything else that needs to be taken care of to get it merged in? I'd be happy to help, I'm just not sure what needs to be done.

**Comment by mikelehen** [comment]
I haven't dug into these changes deeply but as written it seems to _replace_ the existing CodeMirror-based rich-text support, which would break existing users.  It also makes a lot of changes to core internals (in addition to adding rich-text-quill-adapter.js). See all the "amend to support quill" comments...  I'm not sure why all these changes were necessary and if they'll conflict with existing functionality or not.

So if we can rework the PR to _add support_ for Quill without breaking any existing functionality and ideally with minimal changes outside of adding rich-text-quill-adapter.js, then that would be pretty awesome and I'd be happy to review it and work towards getting it merged.

To be clear, ideally this PR would just add rich-text-quill-adapter.js, tweak lib/firepad.js to be able to instantiate it for use with Quill, and then add a new examples/quill.html example or similar.  See [this PR](https://github.com/firebase/firepad/pull/299/) adding support for monaco editor for inspiration.  I'm concerned about all the additional changes as-is.

**Comment by kfoxb** [comment]
Thanks for the quick reply @mikelehen, that was very helpful. As soon as I get some time I'll take a look and see if I can adjust the pull request to only add things as you mentioned.

**Comment by seanfcarroll** [comment]
Would be great to see this go through.

**Comment by seanfcarroll** [comment]
Any movement on this? Cheers

**Comment by kfoxb** [comment]
I'm sorry I haven't worked on this in months, you can check out my fork here: https://github.com/kfoxb/firepad.

It worked when I last worked on it, but still needs a lot of work before it can be merged in. It is still on my radar, but not a priority for me so it may not get done in a while :-/

**Pull request closed without merging**
