### PR TITLE
Disabling drag / drop in ace no longer needed

### LINKED ISSUE #36: Dragging text doesn't properly delete the old text for other clients.
Reported by Guy.  The drag/drop works correctly on the local client, but on other clients they only get the insert.  Not sure why.  I either need to fix that or disable drag/drop (ondragstart='return false;').

### PR DESCRIPTION
**Pull request by adamjimenez**
fixes #36

### CODE REVIEW

**Comment by samtstern** [comment]
@adamjimenez thanks for the pull request.  Do you know why this is working now?  Maybe we could add a test to make sure it works, or at least find out when it started working?

**Comment by adamjimenez** [comment]
It's been working for many versions now. I've been manually undoing this change each time I update for some time.

**Comment by samtstern** [comment]
Tested it locally, looks like it works great!  Here's a screen recording as evidence:
https://drive.google.com/file/d/1t3T3lraog1u17XlXA3GXIyVjai_Jq3ti/view?usp=sharing

**Comment by samtstern** [comment]
This change was released in version `1.5.11`

**Pull request merged**
