### PR TITLE
Export DB Adapter

### PR DESCRIPTION
**Pull request by jamesgibson14**
Exporting this so it is possible to plug in a different DB/messaging adapter.

### CODE REVIEW

**Comment by jamesgibson14** [comment]
I signed it.

**Comment by jamesgibson14** [comment]
I use firepad with Meteor and I would use this to override the
FirebaseAdapter with a new transfer module, example: I am working a redis
channel adapter and also a Meteor Collection adapter to use firepad within
the Meteor env.  I really like the cooperative functionality of firepad but
I can't use firebase in my stack.  This could also be extended for other
Adapters (mysql, pusher.com, rabbitmq)

On Thu, May 3, 2018 at 8:44 AM, Michael Lehenbauer <notifications@github.com

**Comment by mikelehen** [comment]
Ohh... Fascinating!  I like that idea but I'm still fuzzy on how this export will enable that.  Do you have something working already?  How exactly do you make use of this export?  The only thing I could imagine is that in your code you do something like:

```
Firepad.FirebaseAdapter.prototype.sendOperation = function(...) { 
  // my own adapter implementation...
};
```

But I don't think that actually works out because you'd want to override the constructor too.  And so it _seems like_ you'd additionally need to change https://github.com/jamesgibson14/firepad/blob/734b351959de4ffe7d78d56790d14e4ad202ad64/lib/firepad.js#L82 to construct this exported Firepad.FirebaseAdapter instead of the internally-referenced one. That way your own adapter constructor would get called. But that code would still be passing in a Firebase reference so it still seems problematic...

But maybe I'm misunderstanding what you're doing.  Can you elaborate on how you use this?  Or if this is still in development, maybe send a PR once you have it working as desired and then I can take a look?

Thanks!

**Comment by jamesgibson14** [comment]
I was thinking of just overwriting the whole adapter:
Firepad.FirebaseAdapter = MeteorCollectionAdapter, I am not 100% sure that
will work... right now I am just editing the whole repository, but it would
be nice if was changed to "plugin style adapter" firepad(dbref, editor,
{DbAdapter: MeteorCollectionAdapter}), but I was just going for something
simple at first exposing the FirebaseAdapter.

On Thu, May 3, 2018 at 9:47 AM, Michael Lehenbauer <notifications@github.com

**Comment by jamesgibson14** [comment]
Okay sounds good, I will hopefully update soon.

**Comment by robwheatley** [comment]
I'm glad I stumbled across this. I have a similar situation.

I've created an app using Meteor, and thought that it would be great to make the notes part of my app fully collaborative. 

After lots of research into building my own collaborative editor, I decided that it would be too big a task for a 'nice to have'. Then I came across Firepad (which is awesome by the way).

That got me looking at Firebase (never really looked at it before) and I've been playing with Firepad for a couple of days working out how best to integrate it into my Meteor app.

Option 1 was to port the whole thing from Meteor into Firebase, but that's a whole bunch of work and a whole bunch of new stuff to learn, so I threw that idea overboard.

Option 2 was to use Firebase for the notes part of my app, but stick to Meteor for the rest. I've worked out how to do this on paper, but not started implementing just yet. The biggest downside is the fact that I will end up with my app data in 2 separate systems, but I also have lots of obstacles to overcome with authentication and security. 

However, I just thought of an option 3. Perhaps I could simply change all the calls in firepad that are talking to Firebase DB, and update them to Meteor Collections calls - simple right... ;-)

5 mins into scouring your code to gauge how 'easy' that would be, I decided to see if anyone else has done it and came across this thread.

@jamesgibson14 did you get anywhere with this?

**Comment by jamesgibson14** [comment]
No I have not had time to work on it... unfortunately.

**Comment by corwin-of-amber** [comment]
This is a pretty cool idea and could be achieved if you export a bunch of stuff from the `firepad` namespace. I have created [a gist](https://gist.github.com/corwin-of-amber/12671bc8b7ca34f69b25d40d1d6a7d3d) showing a bare-minimum adapter that synchronizes two CodeMirror instances without Firebase.

The first line shows what objects I used.

**Comment by fameintel** [comment]
wow, thanks for sharing that gist. I never got the chance to go through the whole DBAdapter like you did to abstract out the need functions.  I am going to try this out again.

**Comment by corwin-of-amber** [comment]
You're very welcome. Indeed the Firepad devs were very good at separating concerns (kudos guys). Perhaps it would make sense to separate the core client into a separate package, e.g. `firepad-core`, so that it can be used without the Firebase adapter.

**Comment by corwin-of-amber** [comment]
I have had the time to start [firepad-core](https://github.com/corwin-of-amber/firepad-core), by forking firepad and making a few surgical changes. I plan to remove the Firebase adapter and move it to a separate package, hopefully that won't make it too hard to synchronize with the mother repo.

**Pull request closed without merging**
