### PR TITLE
Fixed auth example JSON

### PR DESCRIPTION
**Pull request by mikegrima**
Fixing issues with the example authentication JSON. A random key ID is sent to the database that needs to be permitted.

### CODE REVIEW

**Comment by samtstern** [comment]
@mikegrima thanks for this contribution!  It's been a while since I looked at these examples, can you point to what's broken?

**Comment by mikegrima** [comment]
It throws access denied errors to the database since the path is prefixed with the random key id.

**Comment by samtstern** [comment]
Ok looks like that's here:
https://github.com/FirebaseExtended/firepad/blob/9e70ccdf0bf8810a07c1101d202bbd0de6b1f494/examples/firepad.rb#L16

**Comment by mikelehen** [comment]
Heya...  Thanks for the contribution.  I'm not sure if this change is quite the best though...

That example rules file says "/* Example assumes your Firepad is at the root of your Firebase Database. */" at the top... but that's no longer true. :-) .  There's actually a second example https://github.com/FirebaseExtended/firepad/blob/master/examples/security/secret-url.json which I think would have worked for you as-is.  It's an example of putting your firepad instances under a secret id, which is what the example you were looking at probably does.

I think maybe we should revert this change or else rework the comment (maybe we should just combine the two examples or something).

**Comment by mikegrima** [comment]
Hello:

I wouldn't call it a secret URL That key is randomly generated by firebase.io whenever a user visits to create a "coder space" for which **authenticated** users can make contributions.

I installed a vanilla configuration and copied and pasted the JSON to the firebase database rules and it was being blocked because of the URL pattern. I was making use of the included ACE editor example.

Using the JSON in this PR corrected the permission denied errors.

**Comment by mikegrima** [comment]
I should add more clarification:

When I think of "secret URL", I think of Google Docs where you can make a document public -- but accessible via it's URL only. That was my assumption of what "secret-url" meant. Hence, my usage of `validate-auth.json`.

In my case, I want to have ALL users authenticated before accessing the site. Unfortunately, this was not terribly straightforward to set up, and there is a lack of examples on how to do this with the vanilla code provided (some JavaScript editing was required to make this work -- would love some better examples). 

The provided ACE editor was, by default, prepending a randomly generated ID to all requests, thus throwing permission denied errors.

**Comment by samtstern** [comment]
@mikelehen sorry my merge was hasty, I should have asked you first but it seemed simple enough, apparently not!

@mikegrima I am going to revert the PR and let you and @mikelehen finish discussing before we (hopefully) re-merge it.

**Comment by mikelehen** [comment]
@mikegrima Maybe there's an improvement we can make to the README.md file for https://github.com/FirebaseExtended/firepad/tree/master/examples/security (describe the rules better and/or maybe call out that secret-url.json is the one that's directly compatible with the way the examples/*.html are set up)?  We could also update the comments in the rules files to be more explicit?

**Comment by mikegrima** [comment]
👍 That makes sense. I'm happy to send over a PR to update the readme.

Do you all have some good javascript examples though for adding auth (Google, etc.) to the examples? I'm very new to Firebase as a whole so there was a bit of a learning curve involved in getting this properly up and running -- especially when you have to navigate between the Firebase console and the GCP console.

**Comment by mikelehen** [comment]
Other than the security rules file, we don't really have any examples to help you integrate Firebase Auth with firepad...  and so if you're new to Firebase, there will definitely be a learning curve.  I wouldn't be opposed to having a firepad+auth example, but it seems like it might be kind of involved. The existing examples are really just barebones examples to demonstrate the capabilities of firepad.

That said, we _do_ want firepad to be easy to use and use securely, and it sounds like you had a bumpy getting started experience, so I'm interested in adding docs / links / etc. that would have helped keep you on the right track.  (Or if you do want to contribute an example with auth + firepad, I'm happy to take a look).

FWIW- As far as I know, you should be able to do all the firepad / Firebase Auth stuff from just the Firebase Console, but if you're used to working in the GCP console, I could see how switching to the Firebase console would be a little jarring.

Thanks!

**Pull request merged**
