### PR TITLE
Accept multiple arguments in monaco editor change handler

### PR DESCRIPTION
**Pull request by oliverlin**
### Description

This should fix when receiving multiple arguments in the monaco editor change handler. Related issue: https://github.com/FirebaseExtended/firepad/issues/305

### Code sample

To reproduce the error: 
1. enter some characters
2. select few characters
3. type `{` then it will receive an error in the console

### CODE REVIEW

**Comment by samtstern** [comment]
@oliverlin thanks!  Could you remove the `yarn.lock` file?  We just use plain `npm install` here so you'll noticed there is a `package.json` lock file already.

**Comment by samtstern** [comment]
@mikelehen this LGTM, any thoughts here?

**Comment by garytryan** [comment]
Just user tested this - seems to work

**Comment by derektlo** [comment]
+1 looks good to me

**Comment by oliverlin** [comment]
@samtstern `yarn.lock` has been removed. Thank you!

**Comment by mikelehen** [comment]
LGTM.  Thanks!  If you get a chance, can you add entries to changelog.txt for your changes?  That'll make the release easier for us. :-) Something like:
```
fixed - Fixed an issue in the monaco adapter that could cause errors for certain kinds of edits (#312).
fixed - <whatever the (_this.otherCursors[clientId] || []) change is fixing, or is it related to the same issue?... >
```

Else, no worries. Sam or I can do it later, though it'd help if you could comment on the second fix.

**Comment by oliverlin** [comment]
The second one was added when I found `_this.otherCursors[clientId]` would be `null` under some cases when there are multiple users are editing the file. But I can not reproduce it now. Do you want me to remove it first?

**Comment by oliverlin** [comment]
I pulled the second part `(_this.otherCursors[clientId] || [])` out since it is not related to this issue and added an entry to the `changelog.txt`. Thanks. :)

**Comment by samtstern** [comment]
LGTM, merging!

**Pull request merged**
